Repository Grasscutters/Grasscutter, pull requests merged in 2022-05, with the labels that each got.

#702 Update com.google.code.gson 2.8.8 -> 2.9.0
  build.gradle
Labels: bug

#688 Improve logging pattern by including caller class name
  src/main/resources/logback.xml
Labels: enhancement

#795 [Feature] Stamina: claymore charged attacks
  src/main/java/emu/grasscutter/game/managers/StaminaManager/StaminaManager.java
Labels: feature

#814 Improve text
  src/main/resources/languages/zh-CN.json
Labels: enhancement, language

#549 new command join and remove to force join or remove avatars into your current team
  src/main/java/emu/grasscutter/command/commands/JoinCommand.java
  src/main/java/emu/grasscutter/command/commands/RemoveCommand.java
  src/main/resources/languages/en-US.json
  src/main/resources/languages/zh-CN.json
  src/main/resources/languages/zh-TW.json
Labels: enhancement, feature, commands

#868 Refactor 'dispatch' server/Update plugin authentication API
  build.gradle
  src/main/java/emu/grasscutter/Configuration.java
  src/main/java/emu/grasscutter/Grasscutter.java
  src/main/java/emu/grasscutter/auth/AuthenticationSystem.java
  src/main/java/emu/grasscutter/auth/Authenticator.java
  src/main/java/emu/grasscutter/auth/DefaultAuthentication.java
  src/main/java/emu/grasscutter/auth/DefaultAuthenticators.java
  src/main/java/emu/grasscutter/auth/ExternalAuthenticator.java
  src/main/java/emu/grasscutter/game/gacha/GachaBanner.java
  src/main/java/emu/grasscutter/plugin/Plugin.java
  src/main/java/emu/grasscutter/plugin/api/ServerHook.java
  src/main/java/emu/grasscutter/scripts/serializer/LuaSerializer.java
  src/main/java/emu/grasscutter/server/dispatch/AnnouncementHandler.java
  src/main/java/emu/grasscutter/server/dispatch/ClientLogHandler.java
  src/main/java/emu/grasscutter/server/dispatch/DispatchServer.java
  src/main/java/emu/grasscutter/server/dispatch/authentication/AuthenticationHandler.java
  src/main/java/emu/grasscutter/server/dispatch/authentication/DefaultAuthenticationHandler.java
  src/main/java/emu/grasscutter/server/dispatch/http/AnnouncementIndexHandler.java
  src/main/java/emu/grasscutter/server/dispatch/http/GachaDetailsHandler.java
  src/main/java/emu/grasscutter/server/dispatch/http/GachaRecordHandler.java
  src/main/java/emu/grasscutter/server/http/HttpServer.java
  src/main/java/emu/grasscutter/server/http/Router.java
  src/main/java/emu/grasscutter/server/http/dispatch/DispatchHandler.java
  src/main/java/emu/grasscutter/server/http/dispatch/RegionHandler.java
  src/main/java/emu/grasscutter/server/http/handlers/AnnouncementsHandler.java
  src/main/java/emu/grasscutter/server/http/handlers/GachaHandler.java
  src/main/java/emu/grasscutter/server/http/handlers/GenericHandler.java
  src/main/java/emu/grasscutter/server/http/handlers/LogHandler.java
  src/main/java/emu/grasscutter/server/http/objects/ComboTokenReqJson.java
  src/main/java/emu/grasscutter/server/http/objects/ComboTokenResJson.java
  src/main/java/emu/grasscutter/server/http/objects/HttpJsonResponse.java
  src/main/java/emu/grasscutter/server/http/objects/LoginAccountRequestJson.java
  src/main/java/emu/grasscutter/server/http/objects/LoginResultJson.java
  src/main/java/emu/grasscutter/server/http/objects/LoginTokenRequestJson.java
  src/main/java/emu/grasscutter/server/packet/send/PacketPlayerLoginRsp.java
  src/main/java/emu/grasscutter/utils/ConfigContainer.java
  src/main/java/emu/grasscutter/utils/Utils.java
  src/main/resources/languages/en-US.json
Labels: enhancement, dispatch, breaking

#742 Fixed grammar in README.md #740
  README.md
Labels: documentation, enhancement
